version: '3.1'
services: 
 backend:
   build:  
    context: .
   ports: 
    - "5000:5000"
   environment: 
    MYSQL_HOST: mysql
    MYSQL_USER: admin
    MYSQL_PASSWORD: test@123
    MYSQL_DB: myDb
   depends_on: 
     - mysql
 mysql: 
  image: mysql:5.7
  ports: 
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: myDb
    MYSQL_PASSWORD: test@123
  volumes: 
    - mysql-data:/var/lib/mysq
    - .message.sql:/docker-entrypoint-initdb.d/message.sql

volumes:
  mysql-data:
      

